name: Lint, Test, Build

on:
  pull_request:
  push:
    branches:
      - "*"
      - "!main"

jobs:
  lint-test-build:
    name: Lint, test, and build
    runs-on: ubuntu-latest
    container: zaksabeast/devkitarm-rust
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Lint
        run: make lint

      - name: Test
        run: make test

      - name: Build
        run: make

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: PokeReader
          retention-days: 3
          path: out/default.3gx
