name: Lint, Test, Build

on:
  pull_request:

jobs:
  lint-test-build:
    name: Lint, test, and build
    runs-on: ubuntu-latest
    container: zaksabeast/devkitarm-rust
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Add 3ds target
        run: rustup toolchain install nightly --component rust-src --component clippy

      - name: Lint
        run: make lint

      - name: Test
        run: make test

      - name: Build
        run: make

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: PokeReader
          retention-days: 3
          path: out/pokereader.3gx
